// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR1hCKeh0BRwoHNc_hOLIzvOkpmqGFsRU',
    appId: '1:305483391565:web:b3aa9839c1d450735eb204',
    messagingSenderId: '305483391565',
    projectId: 'chattapp-d15cb',
    authDomain: 'chattapp-d15cb.firebaseapp.com',
    storageBucket: 'chattapp-d15cb.appspot.com',
    measurementId: 'G-T81SL37P7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzthP9t3g3eqhKpAiys2pTJH2IWCseKk',
    appId: '1:305483391565:android:bf86043916c806885eb204',
    messagingSenderId: '305483391565',
    projectId: 'chattapp-d15cb',
    storageBucket: 'chattapp-d15cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANTN-iTeblNtaEOYgDcoIaljvr_tPvvi8',
    appId: '1:305483391565:ios:0b30a07ed2d695e35eb204',
    messagingSenderId: '305483391565',
    projectId: 'chattapp-d15cb',
    storageBucket: 'chattapp-d15cb.appspot.com',
    androidClientId: '305483391565-vidc4qmb0ci2r4j86gqrs4m4caut0lv9.apps.googleusercontent.com',
    iosClientId: '305483391565-js8bg49rpdnea5rcs5cg922cs6n0l7t4.apps.googleusercontent.com',
    iosBundleId: 'com.nymz.chattapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANTN-iTeblNtaEOYgDcoIaljvr_tPvvi8',
    appId: '1:305483391565:ios:ffe826dccc644de45eb204',
    messagingSenderId: '305483391565',
    projectId: 'chattapp-d15cb',
    storageBucket: 'chattapp-d15cb.appspot.com',
    androidClientId: '305483391565-vidc4qmb0ci2r4j86gqrs4m4caut0lv9.apps.googleusercontent.com',
    iosClientId: '305483391565-ko1343irpip60tn25loarsjagfdi8bet.apps.googleusercontent.com',
    iosBundleId: 'com.nymz.chattapp.RunnerTests',
  );
}
